apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: amd-device-metrics-exporter
  namespace: platform
  labels:
    platform.apolo.us/scrape-metrics: "true"
    app: exporter-amdgpu-metrics-exporter
spec:
  selector:
    matchLabels:
      app: exporter-amdgpu-metrics-exporter
  namespaceSelector:
    matchNames:
      - platform
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
