platform: k8s

# -- Add node selector for the daemonset of metrics exporter
nodeSelector: 
  feature.node.kubernetes.io/amd-gpu: "true"

# -- Tolerations to allow scheduling on tainted GPU nodes
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: platform.neuromation.io/job
    operator: Exists
    effect: NoSchedule
  - key: "amd.com/gpu"
    operator: Exists
    effect: NoSchedule

image:
  # -- repository URL for the metrics exporter image
  repository: docker.io/rocm/device-metrics-exporter
  # -- metrics exporter image tag
  tag: v1.0.0
  # -- metrics exporter image pullPolicy
  pullPolicy: Always
  # -- metrics exporter image pullSecret name
  pullSecrets: ""

service:
  # -- metrics exporter service type, could be ClusterIP or NodePort
  type: ClusterIP
  ClusterIP:
    # -- set port for ClusterIP type service
    port: 5000
  NodePort:
    # -- set port for NodePort type service   
    port: 5000
    # -- set nodePort for NodePort type service  
    nodePort: 32500
  labels:
    platform.apolo.us/scrape-metrics: "true"

# -- configMap name for the customizing configs and mount into metrics exporter container
configMap: "gpu-config"

serviceMonitor:
  enabled: true
  interval: 15s
  path: /metrics
  labels: {}